Fix console menu

diff --git a/src/sbin/opnsense-shell b/src/sbin/opnsense-shell
--- a/src/sbin/opnsense-shell
+++ b/src/sbin/opnsense-shell
@@ -105,16 +105,6 @@ shell)
 	;;
 esac
 
-# endless loop
-while : ; do
-
-# We `set -e' to force exit if we encounter an error.
-# This is mainly useful in case we lose our tty (happens when
-# an ssh connection breaks, for example), in which case our stdout
-# is closed and the `echo' commands in the while loop will silently fail.
-# Failure to exit at that moment would lead to an infinite loop.
-set -e
-
 alias GETTEXT='gettext "OPNsense"'
 MENU_0_07=$(GETTEXT "  0) Logout                              7) Ping host")
 MENU_1_08=$(GETTEXT "  1) Assign interfaces                   8) Shell")
@@ -125,6 +115,16 @@ MENU_5_12=$(GETTEXT "  5) Power off system                   12) Upgrade from co
 MENU_6_13=$(GETTEXT "  6) Reboot system                      13) Restore a backup")
 ENTER_AN_OPTION=$(GETTEXT "Enter an option: ")
 ${CMD_BANNER}
+
+# endless loop
+while : ; do
+
+# We `set -e' to force exit if we encounter an error.
+# This is mainly useful in case we lose our tty (happens when
+# an ssh connection breaks, for example), in which case our stdout
+# is closed and the `echo' commands in the while loop will silently fail.
+# Failure to exit at that moment would lead to an infinite loop.
+set -e
 
 echo
 echo "$MENU_0_07"
